name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        # Mencegah push kalau ada kode yang berantakan
        run: npm run lint

      - name: Run Unit Tests (Jest)
        # Menjalankan test-test yang kita buat tadi (BookCard, AddAuthor, dll)
        run: npm test

      - name: Build Project
        # Kita masukkan env palsu/dummy biar Next.js nggak komplain pas build
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8080
        run: npm run build
  build-docker:
    needs: test-and-build # Nunggu test ijo dulu baru jalanin ini
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t bookstore-frontend:test .